### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by dveeden** [pingcap/tidb-tools#819]
## Bug Report

- [x] github.com/pingcap/tidb (causes build with gotip to fail) #814 
- [x] Azure libs are vulnerable https://github.com/pingcap/tidb-tools/security/dependabot/28 #821 #804
- [x] github.com/BurntSushi/toml #818 
- [x] google.golang.org/grpc #822

**Comment by TopScrew** [comment]
The github.com/Azure/azure-sdk-for-go/sdk/azidentity repository has an indirect dependency, and no direct invocation of related dangerous methods has been detected. For reference, see: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMAZUREAZURESDKFORGOSDKAZIDENTITY-7246767.
